FROM mysql:5.7.15

LABEL org.opencontainers.image.authors="spacest"

ENV MYSQL_DATABASE=bookmarks \
    MYSQL_ROOT_PASSWORD=roomless \
    MYSQL_ROOT_HOSTS=% \
    MYSQL_USER=root \
    MYSQL_ALLOW_EMPTY_PASSWORD=1

EXPOSE 3306
